app:
   concurrent-consumers: 10
   base-dir: ${HOMEPATH:/home}
   input-dir: ${app.base-dir}/data/in
   output-dir: ${app.base-dir}/data/out
   charset: UTF-8
   allowed-file-extensions:  >
      dat

logging:
   level:
      br.com.otavio.data.analysis: DEBUG